"""add missing tables

Revision ID: 6c9ed46d30ba
Revises: 0009_preserve_working_drafts
Create Date: 2026-08-30 14:01:20.417811
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9ed46d30ba'
down_revision: Union[str, Sequence[str], None] = '0009_preserve_working_drafts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_citations_working_active'), table_name='research_citations', postgresql_where='(stage_revision_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_research_citations_working_active'), 'research_citations', ['session_id', 'is_active', 'pinned'], unique=False, postgresql_where='(stage_revision_id IS NULL)')
    # ### end Alembic commands ###
