"""Add research tables

Revision ID: b1f4ea86d35c
Revises: 0006_related_work_evidence
Create Date: 2026-08-23 23:30:56.131794
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f4ea86d35c'
down_revision: Union[str, Sequence[str], None] = '0006_related_work_evidence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
